version: "3.8"

services:
  app:
    build: .
    container_name: anagram-api-local-prod
    ports:
      - "8080:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=false
      - APP_KEY=base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    volumes:
      - ./database:/var/www/html/database
      - ./storage/logs:/var/www/html/storage/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  default:
    name: anagram-network
