version: "3.8"

services:
  app:
    build: .
    container_name: anagram-api-prod
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    volumes:
      - ./database:/var/www/html/database
      - ./storage/logs:/var/www/html/storage/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/v1/anagrams/stats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: anagram-nginx-prod
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro
      - ./storage/logs/nginx:/var/log/nginx
    depends_on:
      - app
    restart: unless-stopped

networks:
  default:
    name: anagram-network
